### ISSUE TITLE
bug: Elastic Beanstalk 배포 후 재로그인을 하지 않으면 Signature has expired

### ISSUE THREAD

**Issue by ssfic3380** [SWM14-Architect/moview-core-service#142]
```
[2023-10-29 16:13:25,113] ERROR in app: Exception on /interview/light [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/moview/decorator/timing_decorator.py", line 10, in wrap
    ret = f(*args, **kwargs)
  File "/app/moview/decorator/validation_decorator.py", line 28, in decorated_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 114, in decorator
    verify_jwt_in_request(optional, fresh, refresh, locations)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 66, in verify_jwt_in_request
    jwt_data, jwt_header = _decode_jwt_from_request("access", locations, fresh)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 260, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/utils.py", line 106, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/jwt_manager.py", line 528, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/tokens.py", line 84, in _decode_jwt
    decoded_token = jwt.decode(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
```

**Comment by ssfic3380** [comment]
재로그인 뿐만 아니라, 평소에도 발생하는 문제인 것으로 확인 됨
